### ISSUE TITLE
Add export to binary function

### ISSUE THREAD

**Issue by hdra** [kennellroxco/elixir2pdf#2]
Currently, the `export/2` function requires a file path for the PDF to be written to. 

But sometimes, you may not want the PDF to be written to file, and use it in memory directly. Would you consider adding an `export/1` function that simply returns the PDF binary so that the consumer can decide what to do with it?

**Comment by jsonkenl** [comment]
Sure, that shouldn't be a problem. I wrote this for a specific use case but would be happy to develop further if it's actually being used by others :)

**Comment by hdra** [comment]
Awesome. I actually made some changes for my own use case as well. Will send a PR after I do some clean up.

BTW, I noticed some trailing whitespaces in the source files, would you be open to cleaning those up as well?

**Comment by jsonkenl** [comment]
Sure, no problem at all.
