### ISSUE TITLE
Question about starting multiple PDF instances at once

### ISSUE THREAD

**Issue by seangeo** [kennellroxco/elixir2pdf#5]
Hi,

I'm looking at using Elixir2PDF in a phoenix application and I noticed while testing that you can't create two instances within the one run time, e.g:

```elixir
iex(1)> pdf = Elixir2pdf.new
New pdf
#PID<0.567.0>
iex(2)> pdf = Elixir2pdf.new
New pdf
** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.567.0>}}
    /Users/seangeo/Development/sendle-couriers-ex/deps/erlguten/src/eg_pdf.erl:128: :eg_pdf.new/0
```

Is this something that should be possible? Is it a problem with erlguten library itself?

Thanks

**Comment by jsonkenl** [comment]
Hey @seangeo, yes that looks to be an issue with the erlguten library. I didn't mess with the instance creation logic. I forked a copy of erlguten and use that as the dependency for this, so if you think you could find a fix on the Erlang side, I'd be happy to make the change so this would work for you.
