### ISSUE TITLE
Update to use the canonical erlguten repository

### ISSUE THREAD

**Issue by pmontrasio** [kennellroxco/elixir2pdf#6]
The canonical erlguten repository seems to be https://github.com/richcarl/erlguten but elixir2pdf uses your own fork, which doesn't have any commit past 2012. The canonical version has commit from 2016.
Would it be possible to make elixir2pdf use that newer version? Thanks

By the way, I realized this version mismatch because the old version outputs an annoying "New pdf" message (an `io.format`) and the new version apparently doesn't (I only read the code).

**Comment by jsonkenl** [comment]
Hey @pmontrasio, I created this for a specific use case so I don't have any plans to update it at this time. You're welcome to fork it and replace the dependency yourself though. I'd be happy to help answer any questions about my code if you run into issues.
